version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    bundler:
      patterns:
      - "*"
      update-types:
      - minor
      - patch
    bundler-major:
      patterns:
      - "*"
      update-types:
      - major
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    github-actions:
      patterns:
      - "*"
      update-types:
      - minor
      - patch
    github-actions-major:
      patterns:
      - "*"
      update-types:
      - major
